### ISSUE TITLE
AttributeError: 'Token' object has no attribute 'tags'

### ISSUE THREAD

**Issue by uahmad235** [ZihanWangKi/CrossWeigh#6]
I am getting the following exception after running the code:

```
Traceback (most recent call last):
  File "flair_scripts/flair_ner.py", line 64, in <module>
    train_with_dev=True)
  File "/home/dell/Desktop/CrossWeigh/venv_crossweigh/lib/python3.6/site-packages/flair/trainers/trainer.py", line 373, in train
    loss = self.model.forward_loss(batch_step)
  File "/home/dell/Desktop/CrossWeigh/venv_crossweigh/lib/python3.6/site-packages/flair/models/sequence_tagger_model.py", line 620, in forward_loss
    return self._calculate_loss(features, data_points)
  File "/home/dell/Desktop/CrossWeigh/flair_scripts/sequence_tagger_with_weights.py", line 27, in _calculate_loss
    first_token_tags = sentence.tokens[0].tags
AttributeError: 'Token' object has no attribute 'tags'
```
I am using **flair v0.7**

**Comment by ZihanWangKi** [comment]
See this [issue](https://github.com/ZihanWangKi/CrossWeigh/issues/5).
